server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: tools-study

  # 数据库配置
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ep-summer-lab-aexdkqjr-pooler.c-2.us-east-2.aws.neon.tech:5432/neondb?sslmode=require
    username: neondb_owner
    password: npg_94JLgONBKbuG
  data:
    redis:
      host: localhost
      port: 6379
      password: 
      database: 0
      timeout: 10000ms
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.study.toolsstudy.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.study.toolsstudy: info
    org.springframework.web: info
    com.study.toolsstudy.mapper: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"

# 自定义配置
app:
  jwt:
    secret: your-secret-key-here
    expiration: 86400000  # 24小时
  redis:
    key-prefix: "tools:study:" 